#!/bin/bash

# Yum update & pkgs
echo "[TASK 1] updates & pkg installs" | tee /tmp/bootstrap.log.steve
echo "task 1 setup started" >> /tmp/bootstrap.log.steve
# yum install -y -q vim git redhat-lsb-core net-tools bind-utils >> /tmp/bootstrap.log.steve
# yum install -y -q epel-release >/dev/null 2>&1
# yum install -y -q gcc zlib-devel bzip2-devel readline-devel sqlite-devel openssl-devel 2>&1


echo "[TASK 2] App-specific config"
# create dirs and whatnot as vagrant user

# next step - install new dpenendencies & Docker
echo "[TASK 3] Installing Docker packages"

# Set up global aliases and exports
echo "[TASK 4] Creating global aliases and functions"

cat >>/etc/bashrc <<EOF
# Generated by Vagrant
# alias vi='vim'
# alias sudo='sudo '
alias lll='ls -halt'
# export EDITOR=vim
# export TERM=xterm
# Generated by Vagrant
EOF

# echo "colorscheme elflord" >> /etc/vimrc

# Enable password authentication
echo "[TASK 5] Enabling password authentication in sshd config"
# sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
# systemctl reload sshd

# Disable SELinux
echo "[TASK 6] Disable SELinux"
setenforce 0
sed -i --follow-symlinks 's/^SELINUX=enforcing/SELINUX=disabled/' /etc/sysconfig/selinux

# Set Root password
echo "[TASK 7] Set root password"
echo "admin" | passwd --stdin root >/dev/null 2>&1

# Disable and stop firewalld
echo "[TASK 8] Disable and stop firewalld"
# systemctl disable firewalld >/dev/null 2>&1
# systemctl stop firewalld

# Update hosts file
echo "[TASK 9] Update /etc/hosts file"
# cat >>/etc/hosts<<EOF
# 192.168.56.61 server1.mac.local server
# 192.168.56.62 client1.mac.local client
# EOF

